const FETCH_CITY_DATA = "FETCH_CITY_DATA"
const SET_CITY_DATA = "GET_CITY_DATA"
const FETCH_STATE_DATA = "FETCH_STATE_DATA"
const SET_STATE_DATA = "SET_STATE_DATA"
const FETCH_LOCALITY_DATA = "FETCH_LOCALITY_DATA"
const SET_LOCALITY_DATA = "SET_LOCALITY_DATA"
const SET_PROPERTY_STATE = "SET_STATE"
const FETCH_POST_PROPERTY = "FETCH_POST_PROPERTY";
const SET_RESPONSE_FOR_POST_PROPERTY = "SET_RESPONSE_FOR_POST_PROPERTY";
const FETCH_AUTOGENERATE_DISCRIPTION = "FETCH_AUTOGENERATE_DISCRIPTION";
const SET_AUTOGENERATE_DISCRIPTION = "SET_AUTOGENERATE_DISCRIPTION";
const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const postpropertyTypes = {
  FETCH_CITY_DATA,
  SET_CITY_DATA,
  FETCH_STATE_DATA,
  SET_STATE_DATA,
  FETCH_LOCALITY_DATA,
  SET_LOCALITY_DATA,
  SET_PROPERTY_STATE,
  FETCH_POST_PROPERTY,
  SET_RESPONSE_FOR_POST_PROPERTY,
  FETCH_AUTOGENERATE_DISCRIPTION,
  SET_AUTOGENERATE_DISCRIPTION,
  CLEAR_RESPONSE
};