import api from "./apiServices";

/**Login API */
const login = (payload: Object) => api.post(`/api/login`, payload);
const postProperty = (payload: Object) => api.post("/property/add", payload);

const userPropDetailsById = (payload: any) => {
  const params = new URLSearchParams(payload).toString();
  return api.get(`/property/one?${params}`);
};
const signup = (payload: Object) => api.post(`/users/signup`, payload);
const search=(payload: Object)=>api.post("/property/search", payload);
const useridProperty = (payload:any)=>{
  const params = new URLSearchParams(payload)
  return api.get(`/property/propertyByUserId/${params}`, payload);
}
const category=(payload:any)=>{
  const params = new URLSearchParams(payload).toString();
  return api.get(`/property/propertyByCategory?sub_category=${params}`)
}
const home = (payload:any)=>api.get("/property/home", payload)
const getAllProductApi = (payload: any) => {
  const params = new URLSearchParams();
  params.append("pageNumber", payload.pageNumber);
  params.append("pageSize", payload.pageSize);

  // console.log("prams", params.toString());
  return api.get(`/property/getAllProperty?${params.toString()}`);
};
const getNearuDataApi = (payload: any) => {
  const params = new URLSearchParams(payload).toString();
  return api.get(`/property/nearu?${params}`);
};

const googleCityAutoComplete = (place: any) => {
  const params = new URLSearchParams(place).toString();
  return api.get(`/property/city?${params}`);
};

const googleLocalityAutoComplete = (place: string) => {
  return api.get(
    `https://maps.googleapis.com/maps/api/place/autocomplete/json?input=${place}&key=AIzaSyCEDp1k2rqt67lzxkvetaemDGp7ieO3rpg`
  );
};

const autoGenerateDiscription = (description: string) => (
api.post("/property/autogenerate-description", { description })
)

const Apis = {
  login,
  postProperty,
  getAllProductApi,
  userPropDetailsById,
  signup,
  search,
  getNearuDataApi,
  googleCityAutoComplete,
  googleLocalityAutoComplete,
  autoGenerateDiscription,
  useridProperty,
  category,
  home,
};

export default Apis;
