export const getAllSearchproperty={
  FETCH_ALL_PROPERTY: "FETCH_ALL_PROPERTY",
  SET_ALL_PROPERTY:" SET_ALL_PROPERTY",
  SEARCH_REQ_FAILED:"SEARCH_REQ_FAILED",
  SET_FILTERS:"SET_FILTERS",
  FETCH_CATEGORY_PROPERTY : "FETCH_CATEGORY_PROPERTY",
  SET_CATEGORY_PROPERTY :"SET_CATEGORY_PROPERTY",
  FETCH_HOME_PROPERTY:'FETCH_HOME_PROPERTY',
  SET_HOME_PROPERTY:"SET_HOME_PROPERTY",
}

